# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoKitExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PhotoKitExample
   pod 'Masonry'
  target 'PhotoKitExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
